- id: morning_kettle_id
  alias: Morning kettle
  trigger:
  - entity_id: sensor.living_room_motion_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: 05:00:00
    before: 07:15:00
    condition: time
  action:
  - data:
      event: boil_kettle
    data_template:
      event: boil_kettle
    service: ifttt.trigger
  - data:
      entity_id: automation.morning_kettle
    service: automation.turn_off
  - delay:
      minutes: 45
  - data:
      entity_id: automation.morning_kettle
    service: automation.turn_on
- id: '1503121451330'
  alias: Alarm_on_automation
  trigger:
  - entity_id: sensor.hall_remote
    platform: state
    to: 4_hold
  action:
  - data:
      device_armed: 'True'
    service: blink.arm_system
  - data:
      message: alarm on!
    service: notify.ios_robins_iphone
- id: '1513338225953'
  alias: Leak automation
  trigger:
  - entity_id: binary_sensor.wipy_water_monitor
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      message: Leak detected!
    service: notify.ios_robins_iphone
- id: '1513346519354'
  alias: House_idle
  trigger:
  - entity_id: binary_sensor.motion_at_home
    for:
      minutes: 5
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: input_boolean.house_idle
    service: input_boolean.turn_on
- id: '1513507538746'
  alias: Doorbell notification
  trigger:
  - entity_id: binary_sensor.doorbell
    platform: state
    to: 'on'
  action:
  - data:
      message: The doorbell was pressed
    service: notify.robins_and_marias_iphones
- id: '1513520328271'
  alias: House_motion
  trigger:
  - entity_id: binary_sensor.motion_at_home
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: input_boolean.house_idle
    service: input_boolean.turn_off
- action:
  - data:
      entity_id: timer.kettle
    service: timer.start
  alias: Kettle on timer
  condition: []
  id: '1518374196815'
  trigger:
  - entity_id: binary_sensor.kettle
    platform: state
    to: 'on'
