## HASS config
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 39
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

frontend:
  javascript_version: es5
discovery:
history:
logbook:
sun:
config:
#cloud:
ios:
python_script:
updater:
  include_used_components: true
#logger:
#  default: debug

###########################################################################
## Zones
zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 200
  icon: mdi:home


zone 1:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 1000
  icon: mdi:worker

zone 3:
  name: Waterloo
  latitude: 51.5032
  longitude: -0.1123
  radius: 200
  icon: mdi:train
###########################################################################

blink:
  username: !secret blink_username
  password: !secret blink_password

camera:
  - platform: generic
    name: PanTiltCam
    still_image_url: http://192.168.0.9:8123/local/capture.jpg

hue:
  bridges:
    - host: 192.168.0.3

http:
  api_password: !secret http_password
  login_attempts_threshold: 5

input_boolean:
  house_idle:
    name: No motion for at least 5 minutes
    initial: off
    icon: mdi:timer

ifttt:
  key: !secret ifttt_key

light:
  platform: hue
  host: !secret hue_ip

mqtt:
  broker: !secret nas_ip

notify:
  - name: robins_and_marias_iphones
    platform: group
    services:
      - service: ios_robins_iphone
      - service: ios_marias_iphone

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

#recorder:
#  db_url: !secret my_sql_nas
recorder:
  db_url: !secret google_sql

timer:
  kettle:
    duration: '00:01:00'

wemo:
  static:
    - 192.168.0.29

###########################################################################
## Includes

script: !include scripts.yaml
switch: !include switch.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
automation: !include automations.yaml
group: !include groups.yaml
