## HASS config
homeassistant:
  name: Home
  latitude: 50.0
  longitude: -0.0
  elevation: 0
  unit_system: metric
  time_zone: Europe/London
  customize: !include customize.yaml

frontend:
#  javascript_version: latest
discovery:
history:
logbook:
sun:
config:
ios:
python_script:
updater:
  include_used_components: true
#logger:
#  default: debug

###########################################################################
## Zones
zone:
  name: Home
  latitude: 50.0
  longitude: -0.0
  radius: 200
  icon: mdi:home


zone 1:
  name: Work
  latitude: 51.00
  longitude: -0.00
  radius: 1000
  icon: mdi:worker

zone 3:
  name: Waterloo
  latitude: 51.5032
  longitude: -0.1123
  radius: 200
  icon: mdi:train
###########################################################################

alarm_control_panel:
  - platform: manual
    pending_time: 30

blink:
  username: !secret blink_username
  password: !secret blink_password

camera:
  - platform: generic
    name: PanTiltCam
    still_image_url: http://192.168.0.9:8123/local/capture.jpg

hue:

http:
  api_password: !secret http_password
  login_attempts_threshold: 5

#influxdb:
#  host: 192.168.0.30

input_boolean:
  house_idle:
    name: No motion for at least 5 minutes
    initial: off
    icon: mdi:timer

input_select:
  bed_selector:
    name: In bed selector
    options:
      - "bed"
      - "up"
    icon: mdi:target

ifttt:
  key: !secret ifttt_key

light:
  platform: hue
  host: 192.168.0.3

mqtt:
  broker: 192.168.0.30
  #broker: m20.cloudmqtt.com
  #port: 17799
  #keepalive: 60
  #username: HASS
  #password: Highcloud1


notify:
  - name: robins_and_marias_iphones
    platform: group
    services:
      - service: ios_robins_iphone
      - service: ios_marias_iphone

#  - name: Telegram
#    platform: telegram
#    api_key: !secret telegram_api
#    chat_id: !secret telegram_chat_id


nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

panel_iframe:
  grafana:
    title: 'Grafana'
    url: 'http://192.168.0.30:3003/dashboard/db/speedtest?edit&tab=general&from=1509256281028&to=1509259950412'

recorder:
  db_url: mysql://hass:xxx@192.168.0.30/homeassistant?charset=utf8

###########################################################################
## Includes

script: !include scripts.yaml
switch: !include switch.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensor.yaml
automation: !include automations.yaml
group: !include groups.yaml
