- platform: tplink
  host: 192.168.0.24

- platform: template    # copy toggle switch example
  switches:
    alarm:
      friendly_name: 'Blink alarm toggle'
      value_template: "{{ is_state('binary_sensor.blink_armed_status', 'on') }}" #T_F
      turn_on:
        service: script.turn_on
        entity_id: script.alarm_on_script
      turn_off:
        service: script.turn_on
        entity_id: script.alarm_off_script
